AWSTemplateFormatVersion: '2010-09-09'
Description: BTG Pactual - Infraestructura Cloud Native para API de Fondos

Parameters:
    Env:
      Type: String
      Default: prod
      AllowedValues: [ dev, staging, prod ]
      Description: Entorno de despliegue

Resources:
  ClientesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub btg-clientes-${Env}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH

  FondosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub btg-fondos-${Env}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH

  TransaccionesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub btg-transacciones-${Env}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub btg-users-${Env}
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireNumbers: true

  ClienteGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: CLIENTE
      UserPoolId: !Ref UserPool

  NotificacionesTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub btg-notificaciones-${Env}


  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub btg-cluster-${Env}

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub btg-fondos-api-${Env}
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: btg-fondos-api
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/btg-fondos:latest
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: !Ref Env
            - Name: AWS_SNS_TOPIC_NOTIFICACIONES
              Value: !Ref NotificacionesTopic
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: btg-dynamo-sns-ses-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt ClientesTable.Arn
                  - !GetAtt FondosTable.Arn
                  - !GetAtt TransaccionesTable.Arn
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref NotificacionesTopic
              - Effect: Allow
                Action:
                  - ses:SendEmail
                Resource: '*'

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/btg-fondos-${Env}
      RetentionInDays: 14

Outputs:
  CognitoUserPoolId:
    Value: !Ref UserPool
  ApiCluster:
    Value: !Ref ECSCluster